#print("hello world" + 24)
#print("hello world" - 24)
#print("hello world" / 5)
print("15")
print("168 Days")
print("2047")
print("34+65")
print("52")
print("94")
print("blakey")
print("dital tech")
print("ghost of tushima")
print("hello world" * 5)
print("hello world")
print("Ms White")
print("top text\nbottom text")
print(10-5.0)
print(100+15)
print(5+10.0)
print(55+65)
print(55.0)
print(44+10)
#int("hello world")
#"H:\python2022\helloworld.py"
#int("hello world")
str(int(5/2))
print("he said that; ammi that is ammi'but my amnes'way wore potanti wanna fly away for a moment iwanna say i dropped four brickes in the ocean kit-kats forever phoning they take a toke'and start zoning")